POST http://123.57.31.62:8080/matchmaker/v1/candidate/add
Content-Type: application/json

{
  "email": "cugses@qq.com",
  "gender": 1
}

#####
POST http://123.57.31.62:80/matchmaker/v1/candidate/updateStatus
Content-Type: application/json

{
  "email": "cugsee@qq.com",
  "status": 1
}

##### http://matcher.space/static/candidate.html
POST http://matcher.space/matchmaker/v1/candidate/add
Content-Type: application/json

{
  "email": "cugses@qq.com",
  "gender": 1,
  "age": 1993
}